# Generated by Django 2.2.3 on 2020-03-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='服务器ip')),
                ('password', models.CharField(max_length=256, verbose_name='服务器密码')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Project', verbose_name='所属项目')),
            ],
        ),
    ]
